# Generated by Django 4.2.8 on 2024-05-20 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('keyword', models.TextField()),
                ('title', models.TextField()),
                ('company', models.TextField()),
                ('url', models.TextField()),
                ('deadline', models.TextField()),
                ('location', models.TextField()),
                ('experience', models.TextField()),
                ('requirement', models.TextField()),
                ('jobtype', models.TextField()),
                ('like_users', models.ManyToManyField(null=True, related_name='like_job_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
